### ISSUE TITLE
[BUG] Not unique mount path of pool-coordinator

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [openyurtio/openyurt#1116]
**What happened**:
Not unique mount path of pool-coordinator

```yaml
                volumeMounts:
                  - mountPath: /var/lib/etcd
                    name: etcd-data
                  - mountPath: /etc/kubernetes/pki # conflict
                    name: dynamic-certs
                    readOnly: true
                  - mountPath: /etc/kubernetes/pki # conflict
                    name: static-certs
                    readOnly: true
```

From https://github.com/openyurtio/openyurt/blob/pool-coordinator-dev/charts/openyurt/templates/pool-coordinator.yaml#L185
@luc99hen
