### ISSUE TITLE
[BUG] kubectl logs to pool-coordinator needs rbac

### ISSUE THREAD

**Issue by Congrool** [openyurtio/openyurt#1176]
**What happened**:

When using `kubectl logs` to get pod log from pool-coordinator, the following error will happen.

```plain-text
Error from server (Forbidden): Forbidden (user=openyurt:pool-coordinator:apiserver, verb=get, resource=nodes, subresource=proxy) ( pods/log yurt-hub-openyurt-e2e-test-worker2)
```

It seems that we do not have rbac rules for `openyurt:pool-coordinator:apiserver`. After creating the following `ClusterRoleBinding` into pool-coordinator, it works.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pool-coordinator-apiserver
subjects:
- kind: User 
  name: openyurt:pool-coordinator:apiserver
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin 
  apiGroup: rbac.authorization.k8s.io
```

It's just a temporary solution. We may need more explict authorization for getting nodes/proxy. Additionally, we also should consider when should we create such RBAC rules for `openyurt:pool-coordinator:apiserver` during deploying pool-coordinator, including `ClusterRole` and `ClusterRoleBinding`.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug
