### ISSUE TITLE
[feature request] Establish the component mechanism of the iot system

### ISSUE THREAD

**Issue by LavenderQAQ** [openyurtio/openyurt#1611]
**What would you like to be added**:
Build the component mechanism of the iot system to support the expansion of components and improve the user experience.

**Why is this needed**:
Now we have support for advanced users to customize their iot systems, refer #1596. In [[Feature Request]provide minimal set of components by default to reduce resource consumption](https://github.com/orgs/openyurtio/projects/14?pane=issue&itemId=23562027), @wawlian gives the most concise set of edgex required components, we will be based on this set of solutions for iot system deployment by default, all other optional components will be included in the component mechanism.
For some novice users, we need to give them a more user-friendly way to deploy edgex extensions, for example:
```yaml
apiVersion: iot.openyurt.io/v1alpha2
kind: PlatformAdmin
metadata:
  name: edgex-sample
spec:
  version: minnesota
  poolName: beijing
  component:
  - edgex-ui
  - edgex-device-onvif-camera
  - edgex-app-metrics-influxdb
  ...
```
My current vision is to first build this mechanism on top of an enhanced auto-collector, bringing all of edgex-compose's officially supported extensions into openyurt. Secondly, we can also build tools like user-developed extensions, or incorporate extensions from other communities, which is the potential of this mechanism.
At the same time, how to balance user-defined configuration and component mechanism is also a problem, at present I think it is more reasonable to support extended components to provide users with modifications, but this aspect may bring some complex processing logic to the iot (especially when removing component), we can discuss these in the future.
**others**
/kind feature
