### ISSUE TITLE
[BUG] network interfaces may change or be even offline

### ISSUE THREAD

**Issue by siredmar** [openyurtio/openyurt#1660]
This issue relates loosely to #1649

## Use Case

The use case is:
- running an edge node (e.g. Raspberry PI) that is connected by either WIFI, mobile LTE, cable or even offline. This may change as the network interface is not stable.
- rebooting the device when complete *offline*. This means that flannel, coredns shall be up and running as well as the workload. Service resolution shall be able for pods that are on the same node, even when the device is completely offline.

I have a kind-based setup (based on the e2e cluster, but modified kube-proxy, service-topology) that looks like this. The cluster has a Raspberry PI connected to it. The bootstrapping works using the local LAN. After that a Pod is scheduled on each node that spins up a VPN based on headscale/tailscale. This creates a new device called `wt0` on each node. The VPN is used, because the Raspberry PI that is connected to my local laptop via LAN won't ever be able to contact the other nodes directly, because they are docker containers within a docker network.

If i use the `wt0` device and tell flannel to use this (--iface=wt0) everything works well until i reboot the system offline. Then flannel won't start not creating the proper pod network. No pod is able to start correctly.

I crated a virtual dummy interface on the Raspberry PI to solve two problems:
1. not stable network interfaces: the device can be connected through any device (LTE, WIFI, Ethernet)
2. flannel won't be able to start up if there is no interface online

The interface is able to route to different subnets like ethernet and VPN.

See details on how `edgefarm0` is created. This script is ran on boot of the Raspberry PI.

<details>

```
#!/bin/bash

# Enable IP Forwarding
echo 1 > /proc/sys/net/ipv4/ip_forward

# Configure edgefarm0
ip link add edgefarm0 type dummy
ip addr add 192.168.2.1/24 dev edgefarm0
ip link set edgefarm0 up

# Add routes
ip route add 192.168.1.0/24 dev eth0
ip route add 100.64.0.0/32 dev wt0

# Set up NAT for eth0
iptables -t nat -A POSTROUTING -s 192.168.2.0/24 -o eth0 -j MASQUERADE

# Set up NAT for wt0
iptables -t nat -A POSTROUTING -s 192.168.2.0/24 -o wt0 -j MASQUERADE

# Display Configuration
echo "edgefarm0 configured with IP: 192.168.2.1/24"
echo "NAT configured for 192.168.2.0/24 subnet"
```

</details>

See the nodes that are connected to the cluster. 

```console
$ k get no -o wide  
NAME                     STATUS   ROLES                  AGE     VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
eagle                    Ready    <none>                 5h30m   v1.22.7   192.168.1.100   <none>        Ubuntu 22.04.1 LTS   5.15.0-1034-raspi   docker://20.10.18
edgefarm-control-plane   Ready    control-plane,master   6h30m   v1.22.7   172.18.0.4      <none>        Ubuntu 21.10         5.15.0-78-generic   containerd://1.5.10
edgefarm-worker          Ready    <none>                 6h29m   v1.22.7   172.18.0.3      <none>        Ubuntu 21.10         5.15.0-78-generic   containerd://1.5.10
edgefarm-worker2         Ready    <none>                 6h29m   v1.22.7   172.18.0.2      <none>        Ubuntu 21.10         5.15.0-78-generic   containerd://1.5.10
edgefarm-worker3         Ready    <none>                 6h29m   v1.22.7   172.18.0.5      <none>        Ubuntu 21.10         5.15.0-78-generic   containerd://1.5.10
```

![image](https://github.com/openyurtio/openyurt/assets/2737320/aac2889b-3a9c-4081-b527-e9dd1115b68c)

## Configuration

On the edgefarm-worker* and edgefarm-control-plane nodes the flannel pod uses the VPN interface `wt0` - this works perfectly. 
On the Raspberry PI the flannel pod uses the `edgefarm0` interface. In my understanding flannel spins up a network upon `edgefarm0` and is able to make the pod network working.

> [!NOTE]
> There is no `raven` installed in this cluster!

## The problem

I have several pods running on the cluster:

```
$ k get pods -o wide        
NAME                                 READY   STATUS    RESTARTS       AGE     IP           NODE               NOMINATED NODE   READINESS GATES
alpine-4qlzz                         1/1     Running   1 (109m ago)   5h9m    10.244.1.3   edgefarm-worker2   <none>           <none>
alpine-l4txp                         1/1     Running   1 (110m ago)   5h10m   10.244.2.3   edgefarm-worker3   <none>           <none>
alpine-ssv6k                         1/1     Running   2 (72m ago)    3h49m   10.244.4.6   eagle              <none>           <none>
alpine-t7vds                         1/1     Running   1 (111m ago)   5h11m   10.244.3.3   edgefarm-worker    <none>           <none>
nginx-deployment-6c5879b75d-h6fw4    1/1     Running   2 (72m ago)    3h49m   10.244.4.5   eagle              <none>           <none>
nginx-deployment2-565c4b566b-w4t5w   1/1     Running   0              5h22m   10.244.3.2   edgefarm-worker    <none>           <none>
root                                 1/1     Running   0              5h16m   172.18.0.2   edgefarm-worker2   <none>           <none>
```

If i want to ping from `alpine-ssv6k` on eagle with `10.244.4.6` the pod `alpine-t7vds` with `10.244.3.3` on edgefarm-worker the ping is timed out. 

```console
$ k exec -it alpine-ssv6k -- ping -c 1 10.244.3.3
PING 10.244.3.3 (10.244.3.3): 56 data bytes

--- 10.244.3.3 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss
command terminated with exit code 1
```

However, it's not completely broken. 
See the tcpdump during the ping of `alpine-ssv6k` on eagle

```console
$ tcpdump | grep ICMP
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
12:57:21.251450 IP alpine-ssv6k > 10.244.3.3: ICMP echo request, id 95, seq 0, length 64
```

And here is the tcpdump of `alpine-t7vds` on edgefarm-worker

```
$ tcpdump | grep ICMP
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
12:58:17.870116 IP 10.244.4.6 > alpine-t7vds: ICMP echo request, id 101, seq 0, length 64
12:58:17.870157 IP alpine-t7vds > 10.244.4.6: ICMP echo reply, id 101, seq 0, length 64
```

This means that flannel is able to to use the `edgefarm0` interface to at least something. 
The ICMP request is transmitted through the pod network to the correct pod. The pod even answers, however this answer won't reach its destination. 

On my laptop running the cluster, i event see in the tcpdump that the ICMP reply is recieved.

```
$ sudo tcpdump -i enp2s0 | grep ICMP
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on enp2s0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
IP 10.244.3.3 > 10.244.4.6: ICMP echo reply, id 108, seq 0, length 64
```

On the Raspberry i can't see any ICMP messages at all on no interface:

```
$ tcpdump | grep icmp
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
```

## Reproduce

You can spin up the same cluster as is do running our cli and spinning up the cluster.

```console
$ git clone git@github.com:edgefarm/edgefarm.git
$ git checkout autonomy-fix
$ cd cmd/local-up
$ go mod tidy
$ go mod vendor
# use optional the `--interface` if the Raspberry PI is not connected to the default interface
$ go run main.go cluster create --skip-applications --skip-base --skip-cluster-dependencies --skip-monitor --skip-network
```

After that you can join the node by following the steps after (note, `eagle` is the hostname of the raspberry)
```
$ go run main.go node join -n eagle
# follow the steps provided by the command
```

> [!NOTE]
> You might want to use https://aliacs-edge-k8s-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com/public/pkg/openyurt/cni/v0.8.0/cni-plugins-linux-arm64-v0.8.0.tgz and unpack the binaries at /opt/cni/bin and use the `--reuse-cni-bin` for the `1yurtadm join` command

Apply the alpine.yaml and the nginx-deployment.yaml

*alpine.yaml*
<details>

```
apiVersion: apps/v1
kind: DaemonSet
metadata: 
  annotations: 
    deprecated.daemonset.template.generation: "1"
  labels: 
    app: alpine
  name: alpine
  namespace: default
spec: 
  revisionHistoryLimit: 10
  selector: 
    matchLabels: 
      app: alpine
  template: 
    metadata: 
      creationTimestamp: null
      labels: 
        app: alpine
    spec: 
      containers: 
      - command: 
        - sleep
        - "12000"
        image: alpine/curl:8.2.1
        imagePullPolicy: IfNotPresent
        name: alpine
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      tolerations: 
      - effect: NoSchedule
        key: edgefarm.io
  updateStrategy: 
    rollingUpdate: 
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate

```

</details>

*nginx-deployment.yaml*

<details>

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/hostname: eagle
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      tolerations:
      - effect: NoSchedule
        key: edgefarm.io
        operator: Exists
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
  labels:
    app: nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      nodeSelector:
        kubernetes.io/hostname: edgefarm-worker
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx
  annotations:
    openyurt.io/topologyKeys: kubernetes.io/hostname
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx2
  labels:
    run: nginx2
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx2
```

</details>

## If everything works

If everything works, then 
- the alpine pod running on eagle is able to `curl nginx.default.svc` when offline and online
- the alpine pod running on eagle is able to `curl nginx2.default.svc` when online

@rambohe-ch thanks for the nice chat!
