### ISSUE TITLE
[feature request]add resources configuration into yurt-manager deployment

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1855]
**What would you like to be added**:
The following configuration has not been added into `yurt-manager.yaml` file under `template`.

https://github.com/openyurtio/openyurt/blob/77a66baa46f66493392992236962cdf5dc40769c/charts/yurt-manager/values.yaml#L35-L41

please add the resource configuration into https://github.com/openyurtio/openyurt/blob/master/charts/yurt-manager/templates/yurt-manager.yaml file as following:

```
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.ports.healthProbe }}
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 10
            failureThreshold: 2
           // add begin
          {{- if .Values.resources }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{- end }}
          // add end
      serviceAccountName: yurt-manager
```

**others**
/kind feature
