### ISSUE TITLE
[Question] about deployment on nodepool

### ISSUE THREAD

**Issue by zijin520** [openyurtio/openyurt#1876]
**What happened**:
My cluster consists of three nodes: master(ubuntu), edge1(ubuntu), edge2(arm64),  edge1 and edge2 are all in nodepool "xian".
When I executed the command bellow, the deployments only created on edge1, I want to know why not on edge2 which is also in xian nodepool.
```
cat <<EOF | kubectl apply -f -
apiVersion: iot.openyurt.io/v1alpha2
kind: PlatformAdmin
metadata:
  name: edgex-sample
spec:
  version: minnesota
  poolName: xian
EOF
```

**What you expected to happen**:
the deployments created on edge1 and edge2 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version: v1.4.0
- Kubernetes version (use `kubectl version`): v1.26.11
- OS (e.g: `cat /etc/os-release`):ubuntu18.04
- Kernel (e.g. `uname -a`):Linux master 5.4.0-152-generic
- Install tools:
- Others:

**others**
/kind question
