### ISSUE TITLE
[feature request]improve hostNetwork mode of NodePool

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1935]
**What would you like to be added**:

- background:

A filter named [hostnetworkpropagation](https://github.com/openyurtio/openyurt/blob/master/pkg/yurthub/filter/hostnetworkpropagation/filter.go) in YurtHub component is used for mutating `pod.spec.HostNetwork` field to true in order to adapt hostNetwork mode NodePool. All pods on nodes in the hostNetwork mode NodePool should share the Host network namespace because cni plugin and component(like flannel) have not been installed in the hostNetwork mode NodePool.

But there is a scenario that pods with hostNetwork=false which use the same ports maybe scheduled to the same node in hostNetwork mode NodePool,  then the filter on the node mutate pod hostNetwork field from false to true, so ports conflict will happen and cause pods start failure. this problem is a out of expectation.
 
- solution:

1. It is not a good idea to mutate pod hostNetwork field to true directly, because this maybe cause pods failure. so i think that it is a good idea to add `NodeAffinity` to pods in order to avoid pods to be scheduled on the nodes in the hostNetwork mode NodePool.

2. Pods which don't want to be scheduled to nodes in hostNetwork mode NodePool should be specified by annotation explicitly, and the pod is `annotation["apps.openyurt.io/exclude-host-network-pool"] = true`

3. A webhook will be added in yurt-manager component for adding NodeAffinity to pods with `annotation["apps.openyurt.io/exclude-host-network-pool"] = true`.  Because all nodes in hostNetwork mode Nodepool have `labels[nodepool.openyurt.io/hostnetwork] = true`, so the NodeAffinity will be as following:

```
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nodepool.openyurt.io/hostnetwork
            operator: NotIn
            values:
            - "true"
```

**others**
/kind feature
