### ISSUE TITLE
[feature request] add --feature-gate flag to yurt-controller-manager

### ISSUE THREAD

**Issue by DrmagicE** [openyurtio/openyurt#212]
**Context**
Hi,  I deployed `openyurt` on a cluster with 2 nodes(1 master and 1 worker) to test the autonomy behaviour. 
After setting-up yurt-controller-manager and yurt-hub, I stop the `kubelet` on the edge side.
The logs form `yurt-controller-manager` shows that the master is entering disruption mode, which is used to protect against master machine network isolation. It will prevent any evictions from happening if master can't see any healthy Node.
```
I0131 09:49:50.770911       1 node_lifecycle_controller.go:1230] Controller detected that all Nodes are not-Ready. Entering master disruption mode.
```
This is because my node name is ending with "master" and the `lifecycle-controller` will not take such node as a worker node:
https://github.com/alibaba/openyurt/blob/288aee566107ce7824669c59bb0b286074528293/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L1004-L1015
I can disable `LegacyNodeRoleBehavior` by adding `feature-gates` flags to `kube-controller-manager`.
> feature-gates: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
```
...
spec:
  containers:
  - command:
    - kube-controller-manager
    - --allocate-node-cidrs=true
    - --feature-gates=LegacyNodeRoleBehavior=false <-- adding this line 
...
```
But the `openyurt` seems does not has such flag:
```
...
unknown flag: --feature-gates
```
**What would you like to be added**:
Add `--feature-gates` flag to `yurt-controller-manager`.

**Why is this needed**:
There should be a way to configure feature gates.
