### ISSUE TITLE
[BUG] YurtAppSet: Multiple workloadTweaks interact with each other

### ISSUE THREAD

**Issue by shyer** [openyurtio/openyurt#2203]
**What happened**:
```
    workloadTweaks:
      - pools:
        - f10-inner
        tweaks:
          replicas: 2
      - pools:
        - f10-pub
        tweaks:
          replicas: 3
```
all deployments.apps replicas change to 3:
![image](https://github.com/user-attachments/assets/c9c9662d-92df-4ca0-8824-cca7b15e216d)

**What you expected to happen**:
should not interact with each other

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: apps.openyurt.io/v1beta1
kind: YurtAppSet
metadata:
  name: appset-whoami
spec:
  revisionHistoryLimit: 5
  pools:
    - f10-pub
    - f10-inner
  workload:
    workloadTemplate:
      deploymentTemplate:
        metadata:
          labels:
            app: appset-whoami
        spec:
          selector:
            matchLabels:
              app: appset-whoami
          template:
            metadata:
              labels:
                app: appset-whoami
            spec:
              tolerations:
              - operator: Exists
              containers:
                - name: whoami
                  image: traefik/whoami:v1.10
                  ports:
                  - containerPort: 80
                    protocol: TCP
    workloadTweaks:
      - pools:
        - f10-inner
        tweaks:
          replicas: 2
      - pools:
        - f10-pub
        tweaks:
          replicas: 3
```

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug
