### ISSUE TITLE
[feature request]add a controller for managing rbac settings for multiplexer module in Yurthub.

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#2293]
**What would you like to be added**:
In the proposal [Reusing list/watch requests in the nodepool](https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20241211-reuse-nodepool-list-watch-requests.md), leader yurthub will list/watch specified pool scope metadata from cloud kube-apiserver. so we should add rbac configurations which make leader yurthub can list/watch these pool scope metadatas.

each yurthub will apply a client certificate with organization(`openyurt:multiplexer`), and use this client certificate to forward requests for pool scope metadata to leader yurthub or cloud kube-apiserver. so we can prepare clusterrolebinding beforehand as following:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yurt-multiplexer-binding
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: openyurt:multiplexer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: yurt-multiplexer
```

and the controller need to reconcile `NodePool.Spec.PoolScopeMetadata`, then update `yurt-multiplexer` clusterrole.
.
**others**
/kind feature
