### ISSUE TITLE
[Question]安装yurthub node-pool-name是必填的参数吗

### ISSUE THREAD

**Issue by huweihuang** [openyurtio/openyurt#2378]
**What happened**:

安装yurthub latest 版本的时候遇到以下的报错：
```
F0412 12:40:20.259040       1 start.go:70] validate options: node-pool-name is empty
```

node-pool-name是必填的参数吗？如果是，那么yurthub的yaml文件没有修改。

另外这个参数的值 是以下nodepool对象的name吗？

```
apiVersion: apps.openyurt.io/v1alpha1
kind: NodePool
metadata:
  name: worker
spec:
  type: Edge
```

相关的pr: https://github.com/openyurtio/openyurt/pull/2325

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question
