### ISSUE TITLE
[BUG]yurt-tunnel-agent cannot run as expected

### ISSUE THREAD

**Issue by Poorunga** [openyurtio/openyurt#277]
**What happened**:
When I tried to build an openyurt cluster using the `yurtctl` tool, I found that `yurt-tunnel-agent` could not run as expected:
```
➜  ~ _output/bin/yurtctl convert --provider kubeadm --deploy-yurttunnel --cloud-nodes yurt1 \
                  --yurtctl-servant-image dreameagle/yurtctl-servant:latest \
                  --kubeadm-conf-path /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf  
I0424 02:19:07.589537   55340 convert.go:257] mark yurt1 as the cloud-node
I0424 02:19:07.679159   55340 convert.go:431] kube-public/cluster-info configmap already exists, skip to prepare it
I0424 02:19:07.679191   55340 convert.go:332] deploying the yurt-hub and resetting the kubelet service...
I0424 02:20:17.760571   55340 util.go:319] servant job(yurtctl-servant-convert-yurt2) has succeeded
I0424 02:20:17.760716   55340 convert.go:349] the yurt-hub is deployed
```
`yurtctl` printed a successful log, but when I checked `yurt-tunnel-agent` pod, I found that it was not running normally:
```
➜  ~ kubectl get po -n kube-system | grep yurt-tunnel-agent
yurt-tunnel-agent-xslnm                    0/1     CrashLoopBackOff   2          35s
```
I logged into the edge node to check the container log and found that it prompted:
```
F0424 14:12:45.629204       1 agent.go:36] yurttunnel-agent failed: --node-ip is not set
```
I checked `yurt-tunnel-agent` daemontset yaml file:
```
......
spec:
      containers:
      - args:
        - --node-name=$(NODE_NAME)
        command:
        - yurt-tunnel-agent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
......
```
Then I added the `- --node-ip=$(NODE_IP)` args, like this:
```
......
spec:
      containers:
      - args:
        - --node-name=$(NODE_NAME)
        - --node-ip=$(NODE_IP)
......
```
Finally, `yurt-tunnel-agent` pod is up and running:
```
➜  ~ kubectl get po -n kube-system | grep yurt-tunnel-agent
yurt-tunnel-agent-55vqn                    1/1     Running   0          100s
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version: 
version: "1"
- Kubernetes version (use `kubectl version`): 
v1.16.15
- OS (e.g: `cat /etc/os-release`): 
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
- Kernel (e.g. `uname -a`):
Linux yurt1 4.18.0-240.el8.x86_64 #1 SMP Fri Sep 25 19:48:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
