### ISSUE TITLE
[BUG] Edgenode Turns to NotReady, kubelet on It Restart Rapidly

### ISSUE THREAD

**Issue by Windrow** [openyurtio/openyurt#367]
**What happened**:

After executing `_output/local/bin/linux/amd64/yurtctl convert --provider kubeadm --cloud-nodes master` on master node of an established Kubernetes cluster of two nodes, all pods are pulled and started as expected, but the status of the edge node turns to `NotReady`. Check kubelet's log with `journalctl -xeu kubelet` on that device, we can see kubelet keep restart every few minutes.  

**What you expected to happen**:

After conversion, edge node rejoins the cluster, and has it status `Ready`. 

**How to reproduce it (as minimally and precisely as possible)**: (updated due to further investigation)

- Setup a Kubernetes cluster (I did it with kubeadm) 
- Execute `_output/local/bin/linux/amd64/yurtctl convert --provider kubeadm --cloud-nodes master` on master node (called master)
- Reset yurt with `_output/local/bin/linux/amd64/yurtctl convert`
- Reset the cluster (with `kubeadm reset`)
- Setup the Kubernetes cluster again with new credential
- Execute `yurtctl convert` again
- Issue happens

**Anything else we need to know?**:

- If I do the conversion manually following https://github.com/openyurtio/openyurt/blob/master/docs/tutorial/manually-setup.md, everything is fine.
- `/etc/kubernetes/manifests/yurt-hub.yaml` created by `openyurt/yurtctl-servant` is different from what created in this way: https://github.com/openyurtio/openyurt/blob/master/docs/tutorial/manually-setup.md#setup-yurthub
- If I replace `yurt-hub.yaml` with the file used in a manually-setup, the system recovers from the issue.

**Environment**:
- OpenYurt version: V0.4.0
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (e.g: `cat /etc/os-release`):  
Cloud node:  
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

Edge node:  
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

- Kernel (e.g. `uname -a`):  
Cloud node:  
```
Linux node-3 5.4.0-74-generic #83~18.04.1-Ubuntu SMP Tue May 11 16:01:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Edge node:  
```
Linux ubuntu 5.4.0-1036-raspi #39-Ubuntu SMP PREEMPT Wed May 12 17:37:51 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

- Install tools: kubeadm
- Others:

**others**
https://github.com/openyurtio/openyurt/issues/360#issuecomment-865690544

/kind bug

**Comment by Windrow** [comment]
apiVersion: v1							apiVersion: v1
kind: Pod							kind: Pod
metadata:							metadata:
  labels:							  labels:
    k8s-app: yurt-hub						    k8s-app: yurt-hub
  name: yurt-hub						  name: yurt-hub
  namespace: kube-system					  namespace: kube-system
spec:								spec:
  volumes:							  volumes:
  - name: pki						      |	  - name: hub-dir
    hostPath:							    hostPath:
      path: __pki_path__				      |	      path: /var/lib/yurthub
      type: Directory					      |	      type: DirectoryOrCreate
  - name: kubernetes						  - name: kubernetes
    hostPath:							    hostPath:
      path: /etc/kubernetes					      path: /etc/kubernetes
      type: Directory						      type: Directory
  - name: pem-dir					      <
    hostPath:						      <
      path: /var/lib/kubelet/pki			      <
      type: Directory					      <
  containers:							  containers:
  - name: yurt-hub						  - name: yurt-hub
    image: openyurt/yurthub:latest			      |	    image: __yurthub_image__
    imagePullPolicy: Always				      |	    imagePullPolicy: IfNotPresent
    volumeMounts:						    volumeMounts:
							      >	    - name: hub-dir
							      >	      mountPath: /var/lib/yurthub
    - name: kubernetes						    - name: kubernetes
      mountPath: /etc/kubernetes				      mountPath: /etc/kubernetes
    - name: pki						      <
      mountPath: /etc/kubernetes/pki			      <
    - name: pem-dir					      <
      mountPath: /var/lib/kubelet/pki			      <
    command:							    command:
    - yurthub							    - yurthub
    - --v=2							    - --v=2
    - --server-addr=https://__kubernetes_service_host__:__kub |	    - --server-addr=__kubernetes_service_addr__
    - --node-name=$(NODE_NAME)					    - --node-name=$(NODE_NAME)
							      >	    - --join-token=__join_token__
    livenessProbe:						    livenessProbe:
      httpGet:							      httpGet:
        host: 127.0.0.1						        host: 127.0.0.1
        path: /v1/healthz					        path: /v1/healthz
        port: 10267						        port: 10267
      initialDelaySeconds: 300					      initialDelaySeconds: 300
      periodSeconds: 5						      periodSeconds: 5
      failureThreshold: 3					      failureThreshold: 3
    resources:							    resources:
      requests:							      requests:
        cpu: 150m						        cpu: 150m
        memory: 150Mi						        memory: 150Mi
      limits:							      limits:
        memory: 300Mi						        memory: 300Mi
    securityContext:						    securityContext:
      capabilities:						      capabilities:
        add: ["NET_ADMIN", "NET_RAW"]				        add: ["NET_ADMIN", "NET_RAW"]
    env:							    env:
    - name: NODE_NAME						    - name: NODE_NAME
      valueFrom:						      valueFrom:
        fieldRef:						        fieldRef:
          fieldPath: spec.nodeName				          fieldPath: spec.nodeName
  hostNetwork: true						  hostNetwork: true
  priorityClassName: system-node-critical			  priorityClassName: system-node-critical
  priority: 2000001000						  priority: 2000001000

**Comment by Windrow** [comment]
![yurthub_yaml](https://user-images.githubusercontent.com/25237365/123026883-7e178280-d40f-11eb-9b69-d7555589194e.png)

**Comment by rambohe-ch** [comment]
@Windrow Thank you for filing issue.
Would you be able to upload the `/etc/kubernetes/manifests/yurt-hub.yaml` created by openyurt/yurtctl-servant?

**Comment by Windrow** [comment]
@rambohe-ch 

```
root@ubuntu:/etc/kubernetes# cat manifests/yurt-hub.yaml 

apiVersion: v1
kind: Pod
metadata:
  labels:
    k8s-app: yurt-hub
  name: yurt-hub
  namespace: kube-system
spec:
  volumes:
  - name: hub-dir
    hostPath:
      path: /var/lib/yurthub
      type: DirectoryOrCreate
  - name: kubernetes
    hostPath:
      path: /etc/kubernetes
      type: Directory
  containers:
  - name: yurt-hub
    image: openyurt/yurthub:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: hub-dir
      mountPath: /var/lib/yurthub
    - name: kubernetes
      mountPath: /etc/kubernetes
    command:
    - yurthub
    - --v=2
    - --server-addr=https://192.168.0.97:6443
    - --node-name=$(NODE_NAME)
    - --join-token=ghijkl.0123456789101112
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /v1/healthz
        port: 10267
      initialDelaySeconds: 300
      periodSeconds: 5
      failureThreshold: 3
    resources:
      requests:
        cpu: 150m
        memory: 150Mi
      limits:
        memory: 300Mi
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "NET_RAW"]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  hostNetwork: true
  priorityClassName: system-node-critical
  priority: 2000001000
```

I believe it is created based on `common.go`.
