### ISSUE TITLE
[feature request] united-service among nodepools

### ISSUE THREAD

**Issue by wenjun93** [openyurtio/openyurt#390]
**What would you like to be added**:
As yurt-app-manager supports high-level apis to deploy workloads(deployments/daemonsets) in nodepools, we might also need a high-level service api, which can be called united-service, it works by create/delete services to each nodepool.
```
apiVersion: network.openyurt.io/v1alpha1
kind: UnitedService
metadata:
  name: my-svc
spec:
  selector:
    matchLabels:
      key: my-svc
  serviceTemplate:
    metadata:
      annotations:
      labels:
        key: my-svc
      name: my-svc
      namespace: kube-system
    spec:
      externalTrafficPolicy: Cluster
      ports:
      - name: tcp
        port: 80
        protocol: TCP
        targetPort: 80
      selector:
        k8s-app: my-app
      sessionAffinity: None
      type: NodePort
  topology:
      ......
```

after apply the spec, services are expected to be automatically created, each service selects backends in corresponding nodepool:
```
$ kubectl get service

NAME               TYPE           CLUSTER-IP        EXTERNAL-IP      PORT(S)                           AGE
my-svc-beijing     NodePort      192.168.0.10              <none>           80/TCP                           1d
my-svc-hangzhou   NodePort      192.168.0.11              <none>           80/TCP                           1d
```
**Why is this needed**:
In some cases, deployments among nodepools need to expose their own service, instead of shared one common service. United-Service brings convenience that user don't create service in each nodepool one by one.

**others**
/kind feature

@zzguang @rambohe-ch @kadisi comments?
