### ISSUE TITLE
Failed to start yurt controller Pod (evicted)

### ISSUE THREAD

**Issue by alanz2015** [openyurtio/openyurt#609]
#### labels

/kind failing-test

**Comment by alanz2015** [comment]
Follow the manually setup guide of openyurt, failed to kubectl apply -f config/setup/yurt-controller-manager.yaml. Is this yurt controller must be installed on cluster master node? I set up one cluster master, one worker node which intends to run yurt controller, and one worker node (act as edge node) which intends to run yurt hub. Follow the https://github.com/openyurtio/openyurt/blob/master/docs/tutorial/manually-setup.md,  the PODs of yurt-controller are all evicted.

**Comment by rambohe-ch** [comment]
> Follow the manually setup guide of openyurt, failed to kubectl apply -f config/setup/yurt-controller-manager.yaml. Is this yurt controller must be installed on cluster master node? I set up one cluster master, one worker node which intends to run yurt controller, and one worker node (act as edge node) which intends to run yurt hub. Follow the https://github.com/openyurtio/openyurt/blob/master/docs/tutorial/manually-setup.md, the PODs of yurt-controller are all evicted.

@alanz2015 Thank you for raising issue.
Yeah, yurt-controller-manager should be work on master node, and have the following affinity:
```
      affinity:
        nodeAffinity:
          # we prefer allocating ecm on cloud node
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: openyurt.io/is-edge-worker
                operator: In
                values:
                - "false"
```
