### ISSUE TITLE
[Feature Request]About the new field definition of configmap in the filtering framework

### ISSUE THREAD

**Issue by yingjianjian** [openyurtio/openyurt#773]
**What would you like to be added**:
Regarding the discussion of #749 , I feel that the configmap configuration for the custom filtering framework is more complicated. I want to discuss the field definition through this issue

At present, my thoughts are as follows. If you have any questions, please correct me. Welcome to discuss together.:

```
serviceTopologyFilter:
  servicetopology:
   - user_agent: coredns
     name: coredns
     resources:
       - endpointslices
       - endpoints
     verbs:
	- "list"
	- "watch"
	    
   - user_agent: kube-proxy
     name: servicetopology
     resources:
       - endpointslices
     verbs:
       - "list"
       - "watch"
	    
    - user_agent: nginx-ingress-controller
      name: ingresscontroller
      resources:
	- endpoints
      verbs:
	- "list"
	- "watch"
	    
  discardcloudservice:
    - user_agent: kube-proxy
      name: discardcloud
      resources:
         - services
      verbs:
         - "list"
         - "watch"
  	    
  masterservice:
    - user_agent: kubelet
      name: masterservice
      resources:
        - services
      verbs:
        - "list"
        - "watch"

```
**Why is this needed**:
To customize the filter box

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@yingjianjian what fields do end users need to configure in the configmap `kube-system/yurthub-cfg`?

**Comment by yingjianjian** [comment]
In order to improve flexibility, all fields are basically configured. Currently, the fields that need to be defined are user_agent, name, resources, verbs. For the verbs field, I think it can be defined as the default value? I think the configuration of the addons verbs field should be consistent, I don't know if my idea is correct

> @yingjianjian最终用户需要在 configmap 中配置哪些字段`kube-system/yurthub-cfg`？

In order to improve flexibility, all fields are basically configured. Currently, the fields that need to be defined are user_agent, name, resources, verbs. For the verbs field, I think it can be defined as the default value? I think the configuration of the addons verbs field should be consistent, I don't know if my idea is correct

**Comment by yingjianjian** [comment]
> @yingjianjian what fields do end users need to configure in the configmap `kube-system/yurthub-cfg`?

In order to improve flexibility, all fields are basically configured. Currently, the fields that need to be defined are user_agent, name, resources, verbs. For the verbs field, I think it can be defined as the default value? I think the configuration of the addons verbs field should be consistent, I don't know if my idea is correct

**Comment by rambohe-ch** [comment]
> > @yingjianjian what fields do end users need to configure in the configmap `kube-system/yurthub-cfg`?
> 
> In order to improve flexibility, all fields are basically configured. Currently, the fields that need to be defined are user_agent, name, resources, verbs. For the verbs field, I think it can be defined as the default value? I think the configuration of the addons verbs field should be consistent, I don't know if my idea is correct

@yingjianjian Thanks for your feedback. because we want to use resource names as filter name, for example endpoints filter, endpointslices filter etc.  and specified kind of requests of clients can use specified filter. so the format maybe to define as following:
```
filter_{name}:  user-agent1/verb1,verb2#user-agent2/verb1,verb2
```
so if end users want to configure to filter endpoints and endpointslices response of kube-proxy and coredns list/watch requests. the configuration maybe look as following:

```
apiVersion: v1
data:
  cache_agents: ""
  filter_endpoints: "kube-proxy/list,watch#coredns/list,watch"
  filter_endpointslices: "kube-proxy/list,watch#coredns/list,watch"
kind: ConfigMap
metadata:
  name: yurt-hub-cfg
  namespace: kube-system
```
