### ISSUE TITLE
kubectl exec to edge worker nodes joined via yurtadm fails.

### ISSUE THREAD

**Issue by fujitatomoya** [openyurtio/openyurt#990]
**What happened**:

```bash
root@tomoyafujita:~/istio_work/istio-1.15.0# kubectl exec --stdin --tty ubuntu22-deamonset-glcdn -- date
error: unable to upgrade connection: fail to setup the tunnel: fail to setup TLS handshake through the Tunnel: write unix @->/tmp/interceptor-proxier.sock: write: broken pipe
```

**What you expected to happen**:

```bash
root@tomoyafujita:~/istio_work/istio-1.15.0# kubectl exec --stdin --tty ubuntu22-deamonset-x8trn -- date
Wed Sep  7 23:01:52 UTC 2022
```

**How to reproduce it (as minimally and precisely as possible)**:

- setup OpenYurt cloud node with https://openyurt.io/docs/v0.7.0/installation/manually-setup
- join edge woker nodes via `yurtadm` aligned with https://openyurt.io/docs/v0.7.0/installation/manually-setup
- deploy `DaemonSet` as following.

```yaml
root@tomoyafujita:~# cat ubuntu22-daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ubuntu22-deamonset
spec:
  selector:
    matchLabels:
      app: ubuntu22
  template:
    metadata:
      labels:
        app: ubuntu22
    spec:
      containers:
      - name: ubuntu22
        tty: true
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args: ["sleep 3600"]
        imagePullPolicy: IfNotPresent
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      restartPolicy: Always
```

- try to login each pod via `kubectl exec`, e.g) `kubectl exec --stdin --tty ubuntu22-deamonset-glcdn -- /bin/bash`

**Anything else we need to know?**:

**Environment**:
- OpenYurt version: 0.7.0
- Kubernetes version (use `kubectl version`): v1.22.13
- OS (e.g: `cat /etc/os-release`): 

```bash
root@tomoyafujita:~/istio_work/istio-1.15.0# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

- Kernel (e.g. `uname -a`):

```bash
Linux tomoyafujita 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:
- Others:

**others**

/kind bug
